spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: leib.demo.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #yml文件纯数字 要用单引号包起来
    password: 1996Yu0802
    url: jdbc:mysql://8.136.95.29:3306/rrys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

#eureka配置 服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001


info:
  app.name: leib-springcloud
  company.name: leib's company
---
server:
  port: 8001
mybatis:
  type-aliases-package: leib.demo.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #yml文件纯数字 要用单引号包起来
    password: 1996Yu0802
    url: jdbc:mysql://8.136.95.29:3306/rrys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

#eureka配置 服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001


info:
  app.name: leib-springcloud
  company.name: leib's company