spring:
  profiles:
  active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept


#eureka配置 服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: tests
  application:
    name: springcloud-provider-dept


#eureka配置 服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
