spring:
#  autoconfigure:
#    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
  application:
    name: springcloud-provider-dept
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #指定Nacos服务端地址

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #yml文件纯数字 要用单引号包起来
    password: 1996Yu0802
    url: jdbc:mysql://8.136.95.29:3306/rrys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露的监控端点
server:
  port: 8003 #服务端口号
mybatis:
  type-aliases-package: leib.demo.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
##server:
##  port: 8003
#mybatis:
#  type-aliases-package: leib.demo.entity
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#
#
##spring:
##  application:
##    name: springcloud-provider-dept
##  datasource:
##    type: com.alibaba.druid.pool.DruidDataSource
##    driver-class-name: org.gjt.mm.mysql.Driver
##    username: root
##    #yml文件纯数字 要用单引号包起来
##    password: '0000'
##    url: jdbc:mysql://localhost:3306/db3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
##
###eureka配置 服务注册地址
##eureka:
##  client:
##    service-url:
##      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
##  instance:
##    instance-id: springcloud-provider-dept8003
#
#
#info:
#  app.name: leib-springcloud
#  company.name: leib's company
#
#
## Tomcat
#server:
#  port: 8003
#
## Spring
#spring:
#  application:
#    # 应用名称
#    name: springcloud-provider-dept
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    #yml文件纯数字 要用单引号包起来
#    password: 1996Yu0802
#    url: jdbc:mysql://8.136.95.29:3306/rrys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#  profiles:
#    # 环境配置
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        # 服务注册地址
#        server-addr: localhost:8848
#      config:
#        # 配置中心地址
#        server-addr: localhost:8848
#        # 配置文件格式
#        file-extension: yml
#        # 共享配置
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
