server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com  #eureka 服务器 实例名字
  client:
    register-with-eureka: false #是否向eureka注册中心注册
    fetch-registry: false #表示自己为注册中心
    service-url: #监控页面吧
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7001.com:7001/eureka/
